### ISSUE TITLE
Files Not available from source

### ISSUE THREAD

**Issue by skr3178** [nasa/GeneLab_Data_Processing#8]
![image](https://user-images.githubusercontent.com/79299617/189021543-6b161a38-5eea-46d7-85bc-bd1bfc74c507.png)

When I run this code [link](https://github.com/nasa/GeneLab_Data_Processing/tree/27e0607f6abd2c58669ba399a19b774f06243124/RNAseq/GLDS_Processing_Scripts/GLDS-379/GLDS_version_3/ERCC_Analysis)

https://github.com/nasa/GeneLab_Data_Processing/tree/27e0607f6abd2c58669ba399a19b774f06243124/RNAseq/GLDS_Processing_Scripts/GLDS-379/GLDS_version_3/ERCC_Analysis

there are some errors. 
The json files don't appear to be available. 
Thanks in advance

**Comment by asaravia-butler** [comment]
Those processing scripts retrieved the ISA archive file using an api endpoint that has since been retired.

The call to that retired api endpoint has been replaced in the current processing protocol with directly supplying the local ISA archive path:

https://github.com/nasa/GeneLab_Data_Processing/blob/master/RNAseq/Pipeline_GL-DPPD-7101_Versions/GL-DPPD-7101-F.md#10a-evaluate-ercc-count-data-in-python

The ISA archive can be retrieved using one of the following options:

1. Download using the GeneLab website interface:
    https://genelab-data.ndc.nasa.gov/genelab/accession/GLDS-379
2. Download using the GeneLab public API:
    https://genelab.nasa.gov/genelabAPIs

**Comment by skr3178** [comment]
Thank you
